/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { StaticPageLayout } from './StaticPageLayout';

export const TermsPage: React.FC = () => (
  <StaticPageLayout
    eyebrow="Legal"
    title="Terms of Service"
    subtitle={`Last updated: January 2025. These terms govern your use of LoneZen. By creating an account or using the service, you agree to be bound by them.`}
  >
    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">1. Acceptance of terms</h2>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        LoneZen ("we", "us", "our") provides a business management workspace for independent
        professionals. By accessing or using our website and application (collectively, the
        "Service"), you agree to comply with and be bound by these Terms of Service. If you do not
        agree with any part of these terms, you may not use the Service.
      </p>
    </section>

    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">2. Your account</h2>
      <p className="text-[14px] leading-relaxed mb-3" style={{ color: '#6B7280' }}>
        You are responsible for maintaining the confidentiality of your account credentials and for
        all activity that occurs under your account. You must provide accurate and complete
        information when creating an account and keep it up to date.
      </p>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        You must be at least 18 years old, or the age of legal majority in your jurisdiction, to use
        the Service.
      </p>
    </section>

    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">3. Subscriptions & billing</h2>
      <p className="text-[14px] leading-relaxed mb-3" style={{ color: '#6B7280' }}>
        The Starter plan is free. Paid plans are billed monthly in advance and renew automatically
        until cancelled. You may cancel at any time; access continues through the end of the current
        billing period. Fees are non-refundable except where required by law.
      </p>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        We may change pricing with at least 30 days' notice before the change takes effect.
      </p>
    </section>

    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">4. Acceptable use</h2>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        You agree not to misuse the Service — including attempting to access other users' data,
        reverse-engineering the platform, reselling access without written permission, or using the
        Service for any unlawful purpose. We reserve the right to suspend accounts that violate these
        rules.
      </p>
    </section>

    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">5. AI-generated content</h2>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        Proposals, contracts, and other documents generated by LoneZen's AI features are provided
        as drafts for your review. You are responsible for reviewing, editing, and approving any
        content before sending it to clients. AI output may contain inaccuracies and should not be
        relied upon as legal or financial advice.
      </p>
    </section>

    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">6. Intellectual property</h2>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        You retain full ownership of your data — clients, projects, invoices, and documents you
        create. We retain ownership of the Service itself, including software, design, and branding.
        You grant us a limited license to host and process your data solely to operate the Service.
      </p>
    </section>

    <section className="mb-10">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">7. Disclaimers & liability</h2>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        The Service is provided "as is" without warranties of any kind. To the maximum extent
        permitted by law, LoneZen's total liability arising out of your use of the Service is
        limited to the amount you paid us in the twelve months preceding the claim.
      </p>
    </section>

    <section className="mb-4">
      <h2 className="text-[18px] font-semibold tracking-tight mb-3">8. Changes & contact</h2>
      <p className="text-[14px] leading-relaxed" style={{ color: '#6B7280' }}>
        We may update these terms from time to time. Continued use of the Service after changes take
        effect constitutes acceptance. Questions? Contact us at{' '}
        <a href="mailto:legal@lonezen.com" className="underline" style={{ color: '#4D6BFE' }}>legal@lonezen.com</a>.
      </p>
    </section>
  </StaticPageLayout>
);